trigger:
  - development
  - release/*
      
resources:
  repositories:
    - repository: self
    - repository: deployments
      type: git
      name: Cabi.Kubernetes.Deployment.2021

stages:
- template: microservice.yaml@deployments
  parameters:
    REPOSITORY_NAME: 'Cabi.Publishing.ChatGPTPOC.Web'
    PROJECTS:
      - "publishingchatgptpocweb"
    BUILD_ID: $(Build.BuildNumber)